// Copyright 2017-2024 @subwallet/chain-list authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = {
  name: '@subwallet/chain-list',
  path: (import.meta && import.meta.url) ? new URL(import.meta.url).pathname.substring(0, new URL(import.meta.url).pathname.lastIndexOf('/') + 1) : 'auto',
  type: 'esm',
  version: '0.2.60-beta.0'
};
