"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.packageInfo = void 0;
// Copyright 2017-2024 @subwallet/chain-list authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

const packageInfo = {
  name: '@subwallet/chain-list',
  path: typeof __dirname === 'string' ? __dirname : 'auto',
  type: 'cjs',
  version: '0.2.53-beta.1'
};
exports.packageInfo = packageInfo;