const LogosMap: Record<string, string> = {
  'acala': require('./acala.svg'),
  'altair': require('./altair.svg'),
  'astar': require('./astar.png'),
  'basilisk': require('./basilisk.png'),
  'bifrost': require('./bifrost.svg'),
  'calamari': require('./calamari.png'),
  'clover': require('./clover.svg'),
  'genshiro': require('./genshiro.svg'),
  'heiko': require('./heiko.png'),
  'hydradx': require('./hydradx.svg'),
  'karura': require('./karura.svg'),
  'khala': require('./khala.svg'),
  'kilt': require('./kilt.png'),
  'kintsugi': require('./kintsugi.png'),
  'kusama': require('./kusama.svg'),
  'moonbeam': require('./moonbeam.png'),
  'moonriver': require('./moonriver.svg'),
  'parallel': require('./parallel.svg'),
  'picasso': require('./picasso.svg'),
  'pioneer': require('./pioneer.png'),
  'polkadot': require('./polkadot.svg'),
  'quartz': require('./quartz.png'),
  'rmrk': require('./rmrk.jpg'),
  'sakura': require('./sakura.svg'),
  'shadow': require('./shadow.svg'),
  'shiden': require('./shiden.png'),
  'statemine': require('./statemine.svg'),
  'statemint': require('./statemine.svg'),
  'subsocial': require('./subsocial.svg'),
  'zeitgeist': require('./zeitgeist.png'),
  'koni': require('./koni.svg'),
  'default': require('./default.svg'),
};

export default LogosMap;
